version: '3.4'

services:

  simplemoviesdatabase:
    container_name: simplemoviesdatabase
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: SimpleMoviePassword2024!
    ports:
        - 1433:1433
         
  simplemoviesservice:
    container_name: simplemoviesservice
    image: ${DOCKER_REGISTRY-}simplemoviesservice
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
    build:
      context: .
      dockerfile: SimpleMoviesService/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
        - simplemoviesdatabase